DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS repository;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT, 
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, 
  image TEXT
);

CREATE TABLE repository (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL, 
  link TEXT UNIQUE NOT NULL,
  user_id INTEGER
);